#!/bin/bash
#descriptive names for incoming params
configFile=$1
nm=$2
rcvport=$3
inGuid=$4
outGuid=$5
desturl=$6
numSenders=$7
xslt=$8


#environment specific config
#sets all cfg* variables
source $configFile
source DockerOpts


#javaOpts="-Xms300m -Xmx300m"
#gcOpts="-XX:+PrintFlagsFinal -XX:+PrintGCDetails -XX:+UseParallelGC -XX:NewRatio=3 -XX:ParallelGCThreads=8 -XX:+UseCGroupMemoryLimitForHeap -XX:+ShrinkHeapInSteps"

#--- DOCKER CONTAINER: Transform
if [ -z $xslt ]; then
  rcvo=${nm}SndQ
  sndi=${nm}SndQ
else
  rcvo=${nm}XsltQ
  sndi=${nm}SndQ
  port=$(( $rcvport + 5 ))
  docker run -d\
  ${containOpts[*]}\
  -e JAVA_OPTIONS=$javaOpts -p ${port}:${port} --name ${nm}_xslt_c xslt_i\
  --server.port=$port --jms.inputQ=$rcvo --jms.outputQ=$sndi --xslt.name=$xslt\
  ${miscOpts[*]}
fi

#fire up the docker containers
#--- DOCKER CONTAINER: Receiver
docker run -d\
  ${containOpts[*]}\
  -e JAVA_OPTIONS=$javaOpts -p ${rcvport}:${rcvport} --name ${nm}_rcv_c rcv_i\
  --server.port=$rcvport --jms.databaseQ=sqlQ --jms.outputQ=$rcvo --index.fieldList=MSH-10,PID-5,PID-3 --interface.id=$inGuid\
  ${miscOpts[*]}\
  ${serverSslOpts[*]}

#--- DOCKER CONTAINER: Sender
if [ -z $numSenders ]; then
  numSenders=1
fi
for (( i=1; i<=$numSenders; i++ ))
do
  port=$(( $rcvport + 10 ))
  docker run -d\
  ${containOpts[*]}\
  -e JAVA_OPTIONS=$javaOpts -p ${port}:${port} --name ${nm}_snd${i}_c snd_i\
  --server.port=$port --jms.inputQ=$sndi --jms.databaseQ=sqlQ --destination.url=$desturl --maxattempts.send=1 --index.fieldList=MSH-10,PID-5,PID-3 --interface.id=$outGuid\
  ${miscOpts[*]}\
  ${clientSslOpts[*]}
done
