#!/bin/bash
#--- DOCKER CONTAINER: SQL

#-- Epic Configuration
amqBroker=tcp://severusqa-submission1.epic.com:61616
sqlUrl=jdbc:sqlserver://vista-client.epic.com

docker run -d -p 1433:1433 -p 5001:5001 --name sql_c sql_i --jms.inputQ=sqlQ --spring.datasource.url=$sqlUrl --spring.activemq.broker-url=$amqBroker --spring.datasource.password=va
