#!/bin/bash
#descriptive names for incoming params
amqBroker=$1

#javaOpts="-Xms300m -Xmx300m"
javaOpts="-Xms75m"
gcOpts="-XX:+PrintFlagsFinal -XX:+PrintGCDetails -XX:+UseParallelGC -XX:NewRatio=3 -XX:ParallelGCThreads=8 -XX:+UseCGroupMemoryLimitForHeap -XX:-ShrinkHeapInSteps\
 -XX:MetaspaceSize=200m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=25"
#this just crashes the process with 'too many errors'
#gcOpts="-XX:NativeMemoryTracking=summary"






intNm="PCMM"
intGuid=FDD64944-665D-4AAD-9C8A-BAADC496AF2C

#--- DOCKER CONTAINER: PCMM Query Full
port=8433
nm=${intNm}_query_full_c
docker run -e ENV='dev' -d -p ${port}:${port} --memory="1g" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_full\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts

#--- DOCKER CONTAINER: PCMM Query Delta
port=8434
nm=${intNm}_query_delta_c
docker run -e ENV='dev' -d -p ${port}:${port} --memory="600m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_delta\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts

#--- DOCKER CONTAINER: PCMM Query Status
port=8435
nm=${intNm}_query_status_c
docker run -e ENV='dev' -d -p ${port}:${port} --memory="600m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_status\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts

#--- DOCKER CONTAINER: PCMM Get File
port=8436
nm=${intNm}_get_file_c
docker run -e ENV='dev' -d -p ${port}:${port} --memory="600m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --jms.databaseQ=sqlQ --interface.id=$intGuid --spring.activemq.broker-url=$amqBroker\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_file\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts







intNm="AC"

#--- DOCKER CONTAINER: AudioCare Post
port=8533
intGuid=29F55FB8-BE79-431A-9D33-7598F26D6582
nm=${intNm}_post_c
docker run -e ENV='dev' -e MALLOC_ARENA_MAX=4 -d -p ${port}:${port} --memory="1g" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --jms.databaseQ=sqlQ --interface.id=$intGuid --spring.activemq.broker-url=$amqBroker\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/AC_post\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts
# --app.appointments.file.storage=C:/vista/flatfile/files/epictoensemble\

#--- DOCKER CONTAINER: AudioCare Get
port=8534
intGuid=5A62680D-3759-40C5-8C9D-3299B82779C6
nm=${intNm}_get_c
docker run -e ENV='dev' -e MALLOC_ARENA_MAX=4 -d -p ${port}:${port} --memory="600m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --jms.databaseQ=sqlQ --interface.id=$intGuid --spring.activemq.broker-url=$amqBroker\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/AC_get\
 --app.responses.file.storage="\nfs\3day\dps\\"
 $gcOpts $javaOpts
# --app.responses.file.storage=C:/vista/flatfile/files/ensembletoepic\
