#!/bin/bash
#--- DOCKER CONTAINER: SQL
docker run -d -p 1433:1433 --name sql_c sql_i --jms.inputQ=sqlQ --spring.datasource.url=jdbc:sqlserver://vista-client.epic.com --spring.activemq.broker-url=tcp://severusqa-submission1.epic.com:61616 --spring.datasource.password=va
