#!/bin/bash
#descriptive names for incoming params
amqBroker=$1
useSSL=$2

#javaOpts="-Xms300m -Xmx300m"
javaOpts="-Xms75m"
javaOpts="-XX:NativeMemoryTracking=summary"
#gcOpts="-XX:+PrintFlagsFinal -XX:+PrintGCDetails -XX:+UseParallelGC -XX:NewRatio=3 -XX:ParallelGCThreads=8 -XX:+UseCGroupMemoryLimitForHeap -XX:-ShrinkHeapInSteps\
# -XX:MetaspaceSize=200m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=25"
#this just crashes the process with 'too many errors'
#gcOpts="-XX:NativeMemoryTracking=summary"



intNm="PCMM"
intGuid=FDD64944-665D-4AAD-9C8A-BAADC496AF2C

#--- DOCKER CONTAINER: PCMM Query Full
port=8433
nm=${intNm}_query_full_c
docker run -e ENV='dev' -e JAVA_OPTIONS=$javaOpts -d -p ${port}:${port} --memory="400m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_full --keystore.enabled=$useSSL

#--- DOCKER CONTAINER: PCMM Query Delta
port=8434
nm=${intNm}_query_delta_c
docker run -e ENV='dev' -e JAVA_OPTIONS=$javaOpts -d -p ${port}:${port} --memory="400m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_delta --keystore.enabled=$useSSL

#--- DOCKER CONTAINER: PCMM Query Status
port=8435
nm=${intNm}_query_status_c
docker run -e ENV='dev' -e JAVA_OPTIONS=$javaOpts -d -p ${port}:${port} --memory="400m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_status --keystore.enabled=$useSSL

#--- DOCKER CONTAINER: PCMM Get File
port=8436
nm=${intNm}_get_file_c
docker run -e ENV='dev' -e JAVA_OPTIONS=$javaOpts -d -p ${port}:${port} --memory="400m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --jms.databaseQ=sqlQ --interface.id=$intGuid --spring.activemq.broker-url=$amqBroker\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/PCMM_file --keystore.enabled=$useSSL







intNm="AC"

#--- DOCKER CONTAINER: AudioCare Get and Post
port=8533
intGuid=29F55FB8-BE79-431A-9D33-7598F26D6582
nm=${intNm}_get_post_c
docker run -e ENV='dev' -e MALLOC_ARENA_MAX=4 -e JAVA_OPTIONS=$javaOpts -d -p ${port}:${port} --memory="400m" --restart unless-stopped --name ${nm} fxfer_i --server.port=$port\
 --jms.databaseQ=sqlQ --interface.id=$intGuid --spring.activemq.broker-url=$amqBroker\
 --destination.url.get=http://epic31921.dhcp.epic.com:5105/AC_get\
 --destination.url.post=http://epic31921.dhcp.epic.com:5105/AC_post --keystore.enabled=$useSSL

