#!/bin/bash
nm="mon"

#--- DOCKER CONTAINER: Monitor

#descriptive names for incoming params
configFile=$1
monServer=$2


#environment specific config
#sets all cfg* variables
source $configFile
source DockerOpts


docker run -d\
 ${containOpts[*]}\
 --name ${nm}_c mon_i\
 --start.wait=120 --docker.server=$monServer\
 ${miscOpts[*]}
 