#!/bin/bash
#--- Remove all Containers
docker rm -f $(docker ps -a -q)

container=$(docker ps -q -a -f name=_rcv)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=_snd)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=_xslt)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=sql_)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=mon_)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=PCMM_)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=AC_)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
