#!/bin/bash
#--- Remove all Containers except container AMQ
container=$(docker ps -q -a -f name=rcv)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=snd)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=xslt)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
container=$(docker ps -q -a -f name=sql)
if [ ${#container} -gt 0 ] ; then
	docker rm -f $container
fi
