#!/bin/bash
#--- DOCKER CONTAINER: SQL
nm="sql"

#descriptive names for incoming params
configFile=$1


#environment specific config
#sets all cfg* variables
source $configFile
source DockerOpts


docker run -d\
 ${containOpts[*]}\
 -p 1433:1433 -p 5001:5001\
 --name ${nm}_c sql_i\
 --server.port=5001\
 --jms.inputQ=sqlQ --spring.datasource.url=$cfgSqlUrl --spring.datasource.username=$cfgSqlLogin --spring.datasource.password=$cfgSqlPwd --database.pingonstartup=true\
 ${miscOpts[*]}
