#!/bin/bash
#descriptive names for incoming params
configFile=$1

nm="amq"


#environment specific config
#sets all cfg* variables
source $configFile
source DockerOpts


#--- DOCKER CONTAINER: ActiveMQ
docker run -d\
 ${containOpts[*]}\
 -p 8161:8161 -p 61616:61616 --name ${nm}_c amq_i
# ${miscOpts[*]}
 