spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false

monitor:
  rate: " */5 * * * * * "
  ssl:
    keyStoreType: jks
    keyStore: 
    keyStorePassword: 
  jms: 
    uri: http://severusqa-submission1.epic.com:8161/api/jolokia/read/
    username: admin
    password: admin
  messagedb:
    url: http://severusqa-submission1.epic.com:5001/
  interfaces:
    - 
      name: Scheduling INCOMING
      receiver: 
        url: https://severusqa-submission1.epic.com:5100/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5110/
    - 
      name: Errors
      receiver: 
        url: https://severusqa-submission1.epic.com:5200/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5210/
    - 
      name: Orders
      receiver: 
        url: https://severusqa-submission1.epic.com:5300/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5310/
    - 
      name: Scheduling
      receiver: 
        url: https://severusqa-submission1.epic.com:5400/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5410/
    - 
      name: Demographics ADT
      receiver: 
        url: https://severusqa-submission1.epic.com:5500/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5510/
      transform: 
        url: http://severusqa-submission1.epic.com:5505/
    - 
      name: Demographics ORU
      receiver: 
        url: https://severusqa-submission1.epic.com:5600/
        useSsl: true
      sender: 
        url: http://severusqa-submission1.epic.com:5610/
      transform: 
        url: http://severusqa-submission1.epic.com:5605/
    - 
      name: PCMM Query Full
      receiver: 
        url: https://severusqa-submission1.epic.com:8433/adapter/filetransferservice/getter/
        useSsl: true
    - 
      name: PCMM Query Delta
      receiver: 
        url: https://severusqa-submission1.epic.com:8434/adapter/filetransferservice/getter/
        useSsl: true
    - 
      name: PCMM Query Status
      receiver: 
        url: https://severusqa-submission1.epic.com:8435/adapter/filetransferservice/getter/
        useSsl: true
    - 
      name: PCMM Get File
      receiver: 
        url: https://severusqa-submission1.epic.com:8436/adapter/filetransferservice/getter/
        useSsl: true
    - 
      name: AudioCare
      receiver: 
        url: https://severusqa-submission1.epic.com:8533/adapter/filetransferservice/getter/
        useSsl: true
      sender: 
        url: https://severusqa-submission1.epic.com:8533/adapter/filetransferservice/sender/
        useSsl: true
  email:
    fromAddress: thecloud19791979@gmail.com
    toAddress: sleader@epic.com
    password: seanwashere
  smtp:
    host: smtp.gmail.com
    port: 465
  alerts:
    -
      name: sqlQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogADTSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogADTXsltQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogORUSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogORUXsltQ
      queueMax: 20
      consumerMin: 1
    -
      name: errorSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: inschedSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: orderSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: schedSndQ
      queueMax: 20
      consumerMin: 1
  timeBetweenAlerts: 10
---