spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false

monitor:
  rate: " */5 * * * * * " 
  jms: 
    uri: http://severusqa-submission1.epic.com:8161/api/jolokia/read/
    username: admin
    password: admin
  messagedb:
    url: http://severusqa-submission1.epic.com:5001/
  interfaces:
    - 
      name: Scheduling INCOMING
      receiver: 
        url: http://severusqa-submission1.epic.com:5100/
      sender: 
        url: http://severusqa-submission1.epic.com:5110/
    - 
      name: Errors
      receiver: 
        url: http://severusqa-submission1.epic.com:5200/
      sender: 
        url: http://severusqa-submission1.epic.com:5210/
    - 
      name: Orders
      receiver: 
        url: http://severusqa-submission1.epic.com:5300/
      sender: 
        url: http://severusqa-submission1.epic.com:5310/
    - 
      name: Scheduling
      receiver: 
        url: http://severusqa-submission1.epic.com:5400/
      sender: 
        url: http://severusqa-submission1.epic.com:5410/
    - 
      name: Demographics ADT
      receiver: 
        url: http://severusqa-submission1.epic.com:5500/
      sender: 
        url: http://severusqa-submission1.epic.com:5510/
      transform: 
        url: http://severusqa-submission1.epic.com:5505/
    - 
      name: Demographics ORU
      receiver: 
        url: http://severusqa-submission1.epic.com:5600/
      sender: 
        url: http://severusqa-submission1.epic.com:5610/
      transform: 
        url: http://severusqa-submission1.epic.com:5605/
  email:
    fromAddress: thecloud19791979@gmail.com
    toAddress: sleader@epic.com
    password: seanwashere
  smtp:
    host: smtp.gmail.com
    port: 465
  alerts:
    -
      name: demogADTXsltQ
      enqueuedMax: 74
      timer: 1
---