spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false

monitor:
  startWait: 0
  server: localhost
  rate: " */5 * * * * * "
  keyStore: 
    keyStoreType: jks
    keyStore: C:\Vista\flatfile\files\epic31921.jks
    keyStorePassword: 123456
  trustStore: 
    keyStoreType: jks
    keyStore: C:\Program Files\Java\jdk1.8.0_151\jre\lib\security\cacerts
    keyStorePassword: accesscode
  jms: 
    port: 8161
    path: /api/jolokia/read
    username: admin
    password: admin
  messagedb:
    port: 5001
  interfaces:
    - 
      name: Scheduling INCOMING
      receiver: 
        port: 5100
        useSsl: true
      sender: 
        port: 5110
    - 
      name: Errors
      receiver: 
        port: 5200
        useSsl: true
      sender: 
        port: 5210
    - 
      name: Orders
      receiver: 
        port: 5300
        useSsl: true
      sender: 
        port: 5310
    - 
      name: Scheduling
      receiver: 
        port: 5400
        useSsl: true
      sender: 
        port: 5410
    - 
      name: Demographics ADT
      receiver: 
        port: 5500
        useSsl: true
      sender: 
        port: 5510
      transform: 
        port: 5505
    - 
      name: Demographics ORU
      receiver: 
        port: 5600
        useSsl: true
      sender: 
        port: 5610
      transform: 
        port: 5605
    - 
      name: PCMM Query Full
      receiver: 
        port: 8433
        path: /adapter/filetransferservice/getter
        useSsl: true
    - 
      name: PCMM Query Delta
      receiver: 
        port: 8434
        path: /adapter/filetransferservice/getter
        useSsl: true
    - 
      name: PCMM Query Status
      receiver: 
        port: 8435
        path: /adapter/filetransferservice/getter
        useSsl: true
    - 
      name: PCMM Get File
      receiver: 
        port: 8436
        path: /adapter/filetransferservice/getter
        useSsl: true
    - 
      name: AudioCare
      receiver: 
        port: 8533
        path: /adapter/filetransferservice/getter
        useSsl: true
      sender: 
        port: 8533
        path: /adapter/filetransferservice/sender
        useSsl: true
  email:
    fromAddress: thecloud19791979@gmail.com
    toAddress: sleader@epic.com
    password: seanwashere
  smtp:
    host: smtp.gmail.com
    port: 465
  alerts:
    -
      name: sqlQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogADTSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogADTXsltQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogORUSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: demogORUXsltQ
      queueMax: 20
      consumerMin: 1
    -
      name: errorSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: inschedSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: orderSndQ
      queueMax: 20
      consumerMin: 1
    -
      name: schedSndQ
      queueMax: 20
      consumerMin: 2
  timeBetweenAlerts: 10
---