#!/bin/bash

#descriptive names for incoming params
reConfig=$1
rebuildI=$2

if [ -z $reConfig ] ; then
	reConfig=0
fi
if [ -z $rebuildI ] ; then
	rebuildI=0
fi

#Stop all Docker Containers (except ActiveMQ)
cmd/DockerStopC

if [ "$reConfig" -gt 0 ] ; then
	#Remove all containters (except ActiveMQ)
	cmd/DockerRmvC
fi

#delete all docker images and rebuild them, but only if asked to
if [ "$rebuildI" -gt 0 ] ; then
	#Clear all Docker Images
	cmd/DockerClearI
	#Build docker images
	cmd/DockerBuild

	#Docker container ActiveMQ
	cmd/DockerStartAmq
fi

if [ "$reConfig" -gt 0 ] ; then
	#Docker container SQL
	cmd/DockerStartSql
	#Docker container all Interface Instances
	DockerInts
else
	cmd/DockerStartC
fi

#Docker container stats
cmd/DockerStats
