#!/bin/bash
#descriptive names for incoming params
configFile=$1
nm=$2
rcvport=$3
msgCnt=$4
msgRate=$5
msgSrc=$6

#environment specific config
#sets all cfg* variables
source ../$configFile

#defaults
if [ -z $msgCnt ]; then
  msgCnt=100
fi
if [ -z $msgRate ]; then
  msgRate=10
fi
if [ -z $msgSrc ]; then
  msgSrc=/logs/ORU_R01.hl7
fi


#--- DOCKER CONTAINER for a single interface running hammer
docker run -d\
  -v ${cfgHostMdcLogPath}:/logs\
  --name hammer_${nm}_c hammer_i\
  --memory="600m"\
  --destination.url=http://severusqa-submission1:${rcvport}/receive --send.source=${msgSrc} --send.count=${msgCnt} --send.maxrate=${msgRate}
