#!/bin/bash
#descriptive names for incoming params
nm=$1
rcvport=$2
msgCnt=$3
msgRate=$4
msgType=$5

#defaults
if [ -z $msgCnt ]; then
  msgCnt=100
fi
if [ -z $msgRate ]; then
  msgRate=10
fi
if [ -z $msgType ]; then
  msgType="ADT^A01"
fi


#--- DOCKER CONTAINER for a single interface running hammer
docker run -d --name hammer${nm}_c hammer_i --destination.url=http://severusqa-submission1:${rcvport}/receive --message.type=${msgType} --message.count=${msgCnt} --message.rate=${msgRate}
