#!/bin/bash

#--- Stop any active hammer containers
active=$(docker ps -q -f name=hammer)
if [ ${#active} -gt 0 ] ; then
	docker stop $active
fi

#--- Remove all hammer containers
containers=$(docker ps -q -a -f name=hammer)
if [ ${#containers} -gt 0 ] ; then
	docker rm -f $containers
fi

#docker start hammer_c

#--- Remove the hammer image
docker rmi -f hammer_i 

#--- Build the hammer image
cd build
docker build . -t hammer_i
cd ..

#--- Fire up a hammer for each interface
#------Scheduling INCOMING
./DockerHammer insched 5100
#------Errors
./DockerHammer error 5200
#------Orders
./DockerHammer order 5300
#------Scheduling
./DockerHammer sched 5400
#------Demographics ADT
./DockerHammer demogADT 5500
#------Demographics ORU
./DockerHammer demogORU 5600

